name: Cherry-pick request
description: Use this template to cherry-pick commits into a release branch
body:
  - type: markdown
    attributes:
      value: |
        **Note:** Provide commit IDs to cherry-pick into a specific release branch. Once the issue has been created, **please add this to the corresponding release milestone** to trigger the cherry-pick workflow.
  - type: textarea
    id: commit_ids
    validations:
      required: true
    attributes:
      label: >
        Commit IDs
      description: >
        Please enter the commit ID(s) to be cherry-picked. E.g. 9e90a6, f1da12
  - type: dropdown
    id: subteam
    validations:
      required: true
    attributes:
      label: >
        Category
      description: >
        Which category does this issue belong to? Please select the corresponding label(s).
      multiple: true
      options:
        - team-CLI
        - team-OSS
        - team-Core
        - team-Bazel
        - team-Android
        - z-team-Apple
        - team-Rules-API
        - team-Rules-CPP
        - team-Local-Exec
        - team-Rules-Java
        - team-Rules-ObjC
        - team-Loading-API
        - team-Performance
        - team-Remote-Exec
        - team-ExternalDeps
        - team-Rules-Python
        - team-Rules-Server
        - team-Documentation
        - team-Configurability
        - team-Starlark-Integration
        - team-Starlark-Interpreter
  - type: textarea
    validations:
      required: true
    id: reviewer
    attributes:
      label: >
        Reviewers
      description: >
        Please provide reviewers for the cherry-pick PR. E.g. @iancha1992, @bazelbuild/triage
